spring:
 jpa:
   properties.hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
   database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
   hibernate:
      ddl-auto: update
      dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
 datasource:
  url: jdbc:postgresql://192.168.99.100:5432/map_places
  username: admin
  password: secret

server:
 port: 9595

maxCounterUpdateIncreaseAttempts: 10

#Log http requests and responses
logging.level.org.springframework.ws.server.MessageTracing.sent: TRACE
#Log every url mapping at startup
logging.level.org.springframework.web.servlet.mvc.method.annotation: TRACE