//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.19 at 04:42:07 PM EEST 
//


package com.boug.geospatial.dto.generated_soap_dtos;

import lombok.Getter;
import lombok.Setter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pointOfInterestDto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pointOfInterestDto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="capital" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="population" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="requestCounter" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="coordinates" type="{map-points}coordinates"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pointOfInterestDto", propOrder = {
    "city",
    "capital",
    "country",
    "population",
    "requestCounter",
    "coordinates"
})
@Getter
@Setter
public class PointOfInterestDto {

    @XmlElement(required = true)
    protected String city;
    @XmlElement(required = true, nillable = true)
    protected String capital;
    @XmlElement(required = true, nillable = true)
    protected String country;
    @XmlElement(required = true, type = Long.class, nillable = true)
    protected Long population;
    protected long requestCounter;
    @XmlElement(required = true)
    protected Coordinates coordinates;

}
